FROM centos:7

RUN yum update -y && \
    yum install -y \
        openssh-clients \
        openssh-server && \
    yum clean all

# CentOS is missing default keys
RUN ssh-keygen -A

RUN echo $'LogLevel DEBUG3 \n\
PermitRootLogin yes \n\
TrustedUserCAKeys /etc/ssh/user_ca.pub \n\
HostKey /etc/ssh/example.com \n\
HostCertificate /etc/ssh/example.com-cert.pub \n' > /etc/ssh/sshd_config

COPY ./ssh/user_ca-cert.pub /etc/ssh/user_ca.pub
COPY ./ssh/host_ca /etc/ssh/example.com
COPY ./ssh/host_ca-cert.pub /etc/ssh/example.com-cert.pub